#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale ~/.media/the_valley.png

~/.config/polybar/start.sh &


bspc rule -a Spotify desktop='^5' state=pseudo_tiled

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nextcloud &

# Reload sxhkd since some keybindings don't work.
pkill -USR1 -x sxhkd

# Lock screen
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 120 seconds, undim if user becomes active` \
  --timer 120 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .1' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
  `# Undim & lock after 10 more seconds` \
  --timer 10 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; i3lock -c 444444' \
    ''
