#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-scale ~/.media/the_valley.png

~/.config/polybar/start.sh &


bspc rule -a Spotify desktop='^5' state=pseudo_tiled

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nextcloud &

# Reload sxhkd since some keybindings don't work.
pkill -USR1 -x sxhkd

# Fix Jetbrains IDEs
/home/tim/.local/bin/wmname LG3D &

xset s on
xset s 120
xss-lock xsecurelock
env XSECURELOCK_FONT=`xlsfonts | grep '\<iso10646-1\>' | shuf | head -n 1` xsecurelock

